### ISSUE TITLE
Unhandled exception error

### ISSUE THREAD

**Issue by hman1217** [engle2192/PoGoMap-GUI#1]
Hi,

I got this error while trying to create accounts and save my notification settings. If I already have accounts, where do I go to input it in?

**Comment by Go2Engle** [comment]
Could you post a screenshot with the error please? and if you already have accounts you will need to put them in the config file located under .\Pokemongo-map\config\config.ini.

**Comment by hman1217** [comment]
http://imgur.com/a/mstL4

**Comment by Go2Engle** [comment]
Hmmm question: Are you trying to use the exe with an already configured pokemongo-Map? If so this will not work. You will need to download the zip from the release section and use whats packaged with it keeping the folder structure the same.

**Comment by hman1217** [comment]
No I downloaded the zip and released everything

**Comment by Go2Engle** [comment]
Did you run through the install button for the first time? Also looking at the password you are trying to use i believe that is to short. Try using something longer then 7 characters. oh and you must have google chrome installed on your pc.

**Comment by hman1217** [comment]
Yeah I have Chrome as well. Do you have time to help me through screenshare? I ran into powershell problems too and can't run "gpedit.msc"

**Comment by Go2Engle** [comment]
Im currently at work lol. I can in a few hours once i get home. In the mean time try downloading a fresh copy and run through all the steps in the install tab and on the main page of the github and just to be safe reboot PC. If that dosnt work let me know and I'll contact you when I'm home.

**Comment by hman1217** [comment]
Awesome, thank you so much. Yeah let me try it again

**Comment by maxblock** [comment]
I just had a similar problem where a file was missing. In [...]\PoGoMap-GUI\PokemonGo-Map\config there was a file named "config.ini.example". After renaming it to "config.ini", I could successfully run all installation steps.

**Comment by Go2Engle** [comment]
ok question for you both. on the very first run did you do the step 4 under the install section? step 4 renames the config.ini.example to config.ini and inserts your google maps API key. if you dont do this step then that is the reason you would be getting these errors.

**Comment by maxblock** [comment]
Yes, I tried multiple times.

**Comment by Go2Engle** [comment]
ok I think I know why this is happening. Im going to change the way the api key gets inserted into the config file. I'll post in here once I've made the change.

**Comment by Go2Engle** [comment]
Ok sorry to make you do this but please delete your current download and re download the 3.0 zip and give it a try again. made a quick change that should do the trick!

**Comment by maxblock** [comment]
Don't apologise! I'm just happy I won't have to write the GUI myself. Still no dice, I'm afraid; now the error pops up when doing step 4.

**Comment by Go2Engle** [comment]
could you attache a screenshot? its working fine on my end =[

**Comment by maxblock** [comment]
It's throwing a DirectoryNotFoundException when accessing [...]\PoGoMap-GUI\PokemonGo-Map\config.ini (which does not exist), when doing step 4.

**Comment by Go2Engle** [comment]
hmmm if your downloading the zip from https://github.com/engle2192/PoGoMap-GUI/releases/tag/3.0 it should have 1 file and 2 folders in that zip. the .exe, PokemonGo-Map folder, and PokeAlarm folder. where ever you extract the file too it needs to stay in this structure for everything to work properly.

**Comment by Go2Engle** [comment]
Direct link to download: https://github.com/engle2192/PoGoMap-GUI/files/477462/PoGoMap-GUI.v3.0.zip

**Comment by maxblock** [comment]
I must've did something because the config file was missing altogether. Now I manually copied it and setup of accounts worked. However, when adding alarms, "alarms.json" was missing throwing the same exception as above. When running "Run map", python claims the location argument is missing for the mainmethod of pokemongo-map/runserver. Any fix?

**Comment by Go2Engle** [comment]
Thats strange. I just download the zip 5 times to be sure and no files are missing. Are you trying to clone the repo or are you downloading the zip? Have you tried the direct link i posted above?

**Comment by Go2Engle** [comment]
Ohhhh and as for the location argument you just need to put in a zip code or coordinates into the zip code field.

**Comment by maxblock** [comment]
After adding my coordinates into the zip field it seems to find pokemon. Although I can't open the map in my browser. Any ideas why? It's just timing out the connection.

**Comment by mannyluccio** [comment]
engle2192 you plan adding Telegram notification in next days?

**Comment by Go2Engle** [comment]
Sure thing. I should be able to add that this weekend possibly.

**Comment by Go2Engle** [comment]
@maxblock Are you using the view map button?

**Comment by maxblock** [comment]
@engle2192 Edit: Never mind, changed my browser and it started working. Thanks a bunch for the support!
Yes. My browser is opening 192.168.1.6:5000. I also tried changing the port to 8888 (which I know is available) as well as localhost:[port].

**Comment by Go2Engle** [comment]
what browser are you using? Also when the page is opening what error are you getting?

**Comment by maxblock** [comment]
@engle2192 For some reason, it has set Edge to default. Edge claims it cannot connect to the server. However Firefox (v50) connects perfectly.

**Comment by Go2Engle** [comment]
Try changing your default browser on your PC to something other then edge. Edge is poo anyways lol. When using the view map button it opens whichever is your default browser on the PC to http://your_ipaddress:Port_you_chose.

**Comment by maxblock** [comment]
@engle2192 Yes, it's usually Firefox. However, a couple of days ago it had some error when updating and Windows decided Edge was a better default browser for me...

**Comment by Go2Engle** [comment]
@maxblock haha damn windows and making decisions for us!

**Comment by hman1217** [comment]
Now I get preregs error while trying to create accounts. Lmk when you're free to help me, no rush.

**Comment by xzerobutter** [comment]
http://imgur.com/cXRc5UG
what is -enc ?

**Comment by Go2Engle** [comment]
Its a switch in the version of pokemongo-map I'm using. It encounts the pokemon to show you the IV and move sets of each Mon on the map. Are you trying to use my GUI with the official map? If so it wont work. I built this pre configured with everything in my repo.

**Comment by xzerobutter** [comment]
http://imgur.com/2K4vD3R
After I created accounts......??

**Comment by Go2Engle** [comment]
Check your config file and see if the accounts were added. If they were you can just ignore this error. If they weren't added try following the power shell instructions in the readme on the github page.

**Comment by hman1217** [comment]
What re you up to boss?

**Comment by xzerobutter** [comment]
http://imgur.com/Gz27XmA
Could not find file >> alarms.json

**Comment by Go2Engle** [comment]
Everyone please try re-installing using the new AIO installer and run through the last few install steps in the GUI. Let's see if that works now. Made some big changes this morning.

**Comment by hman1217** [comment]
http://imgur.com/a/itV4f hey boss, I got this error after creating 5 accounts. Do u have any idea why?

**Comment by Go2Engle** [comment]
Can you check and see if the usernames were entered into the config file for me. If not let me know and I'll have my power shell dude take a look.

**Comment by hman1217** [comment]
No it's not, do I need to activate them by picking the first pokemon?

**Comment by hman1217** [comment]
do u want to screenshare btw?

**Comment by Go2Engle** [comment]
I can't today. Not home ahhh.

**Comment by Go2Engle** [comment]
And you shouldn't have to. Try running the create accounts one more time. Just make one to try and see if they get added. Be sure to use the same password.

**Comment by hman1217** [comment]
:( Yeah I cant save to config for the notification settings either

**Comment by hman1217** [comment]
Yeah I tried that and checking accounts, both time return banned.py error

**Comment by hman1217** [comment]
Error: need one more value to unpack

**Comment by Go2Engle** [comment]
That's really weird. And your sure you followed the instructions on the github hub? If so I'm not sure what's going on. I'll have to wait till I get some free time to take a look into it or remote in to trouble shoot.

**Comment by Go2Engle** [comment]
@hman1217 do you have a min now for me to remote in?

**Comment by hman1217** [comment]
Yeah I do, should I dm you my skype on reddit?

**Comment by hman1217** [comment]
Sorry my phone didn't give me notifications for some reason

**Comment by Go2Engle** [comment]
Damn I'm actually gone now. I'll reply to this tomorrow. Hopefully we can do it then.

**Comment by hman1217** [comment]
Yeah no problem. What time are u available tomorrow?

**Comment by Go2Engle** [comment]
@hman1217 if your awake right now in the next 10 mins I can look if not ill have to let you know tomorrow.

**Comment by hman1217** [comment]
Lool I missed you by a hair bit again

**Comment by hman1217** [comment]
I'm ready whenever boss

**Comment by Go2Engle** [comment]
Might have to be later today.

**Comment by hman1217** [comment]
No worries, I'll hit u up around 7pm PST, lets go PATRIOTS

**Comment by hman1217** [comment]
hey u still up?

**Comment by hman1217** [comment]
do u have a minute tonight man?

**Comment by hman1217** [comment]
Did you figure out how to fix the shell errors? My accounts don't add to file, even if I added it manually, it won't run

**Comment by Go2Engle** [comment]
Wanna try another fresh install? a few more changes have been made over the days. maybe another fresh install may do the trick

**Comment by hman1217** [comment]
I tried on a new laptop too but same errors :(

**Comment by Go2Engle** [comment]
can you create an account on my forum and PM me. I can remote in quick. www.go2engle.com my username is engle2192
