### ISSUE TITLE
Account Creator Installation Error

### ISSUE THREAD

**Issue by 8BitSnowman** [engle2192/PoGoMap-GUI#11]
I keep receiving this error whenever I attempt to install the account creator

`Command "c:\users\devin\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Devin\\AppData\\Local\\Temp\\pip-build-oqo2hhq4\\cffi\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Devin\AppData\Local\Temp\pip-70pm8bw9-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Devin\AppData\Local\Temp\pip-build-oqo2hhq4\cffi\`

**Comment by Go2Engle** [comment]
hmmm try rebooting your computer and then run the install account creator again.

**Comment by 8BitSnowman** [comment]
That didn't work

**Comment by Go2Engle** [comment]
are you getting this error when trying to run the account creator or when trying to install the account creator?

**Comment by 8BitSnowman** [comment]
When I try to install the account creator

**Comment by 8BitSnowman** [comment]
Hello, I understand if you're busy and I greatly appreciate you taking time to respond but if you have any time available I really would be grateful if you could look into this issue further for me

**Comment by Go2Engle** [comment]
hmmm. Please try to run the below commands in a command window then try the account creator again.

pip install git+https://github.com/sriyegna/pikaptcha

pip install git+https://github.com/keyphact/pgoapi.git
