### ISSUE TITLE
Look externally

### ISSUE THREAD

**Issue by kevintea** [engle2192/PoGoMap-GUI#12]
Hello! I wanted to know how I can do to see this map externally (outside WIFI connection in the house), could guide me in any way? Thank you for this great work, I love it!
Forgive my writing I'm using Translate.

**Comment by Go2Engle** [comment]
No problem. You can follow the guide from the official pokemongo-map. They have some great documentation! 
https://pgm.readthedocs.io/en/develop/extras/external.html

**Comment by kevintea** [comment]
Is there any other possibility? in my country internet providers do not give me access to the control panel of my modem / router to open the necessary ports.

**Comment by Go2Engle** [comment]
Unfortunately I'm not aware of one. I'm sure there's something out there if you look hard I'm sure you could fine someway :)
