### ISSUE TITLE
How do I uninstall it completely to be able to try it again?

### ISSUE THREAD

**Issue by timothyhuang** [engle2192/PoGoMap-GUI#13]
Sorry I'm totally new to this. I received some errors on the install. So I'm trying to uninstall it and try again however when I delete the desktop folder, it doesn't seem to uninstall everything for me to run step 1 again. It just shows up as "already installed" 

Any help would be appreciated. Thanks!!

**Comment by Go2Engle** [comment]
for step one just manually run the below in a cmd window.

Type pip install git+https://github.com/sriyegna/pikaptcha and hit enter

Type pip install git+https://github.com/keyphact/pgoapi.git and hit enter

That will re-install what the first button in step one does.

**Comment by timothyhuang** [comment]
When I try that, it gives me,
" 'pip' is not recognized as an internal or external command, operable program or batch file"

I may have messed something up trying to delete and uninstall the programs earlier so I could start over. Thoughts?

**Comment by Go2Engle** [comment]
Try manually downloading and installing 
https://git-for-windows.github.io/
https://www.python.org/downloads/release/python-2712/
https://www.microsoft.com/en-us/download/details.aspx?id=44266
https://nodejs.org/dist/v4.5.0/node-v4.5.0-x64.msi

then continue from there.

**Comment by timothyhuang** [comment]
Downloaded and installed them via your provided links, but still no luck.... 

Does your program automatically detect where python is installed to etc? Or do I need to link it somehow? The cmd window is still giving e the error of " 'pip' is not recognized as an internal or external command, operable program or batch file"

Thanks for your patience and help on this

**Comment by Go2Engle** [comment]
Ahhh I got an idea when installing python from the link above there is a section in the install that you need to check that says to add python to path. Try reinstalling just python and check that box.

**Comment by timothyhuang** [comment]
Awesome. I think that helped me get through part 1. However now at part 3, it's giving me an error saying the usernames.txt file is missing. Please note, that on my first time through I was able to create accounts no problem. Not sure what's happening now. Also, when I click on run map, it's giving me an error of "python is not recognized as an internal or external command, operable program or batch file"

Is there a way to just uninstall it all and start fresh over? I'm a total noob at this trying to figure this out...
