### ISSUE TITLE
How to expand the records to more than 24 hours ?

### ISSUE THREAD

**Issue by dr-antivirus** [engle2192/PoGoMap-GUI#15]
It's not exactly an issue. 
I just want to know if it is possible to make the Full-stats (full stats) record for more than 24 hours by any programming process ?
I think those informations are too valuable to let them go after 1 day. It would be nice if I can make a 7 days report, of even an all-time database.
Thank you.

**Comment by Go2Engle** [comment]
There should be a drop down box in the top left hand corner that you can change the days?

**Comment by dr-antivirus** [comment]
I see the options thing (I already used it to configurate Chrome notifications and other stuff)
But I don't see any option to save the statistics log duration.
The logs are set to 1 day (24 hours), when you click on top left stats>full stats : 

> POKEMON SEEN IN LAST DAY

I just want to do some larger stats database with records from the 7 previous days, or maybe more.
Where is the code which automatically deletes all records that are older than 24 hours so I can edit it ?

**Comment by Go2Engle** [comment]
Have you been running it longer than one day yet?

**Comment by dr-antivirus** [comment]
Yes. 3 days non-stop.
It's keeping records from the last 24 hours only. All pokemon that have spawned before are automatically being removed from the "full stats"

**Comment by Go2Engle** [comment]
I'll see if there is an update to the map and put it in next release.

**Comment by dr-antivirus** [comment]
Ok thank you !
