### ISSUE TITLE
unexpected error in line 0

### ISSUE THREAD

**Issue by mervinpoh** [engle2192/PoGoMap-GUI#16]
runserver.py: error: Unexpected line 0 in C:\Users\mervin\Desktop\PoGoMap-GUI\PokemonGo-Map\pogom../config/config.ini: ∩╗┐# DO NOT USE NOTEPAD TO EDIT CONFIG FILES!! USE NOTEPAD ++ INSTEAD.

I get this some of the times..
The thing is its line 0.. theres nothing there! what am i doing wrong?

Also if i have a big list of usernames password in the format of username:password

where do i edit to import this acounts?

**Comment by Go2Engle** [comment]
Did you edit the config file with note pad? If so you need to delete it and re download it and only edit it with software like notepad++. Also at the moment there is no good way. Tomorrow I will be releasing 3.1.6. When I do it will support csv files for usernames and passwords. So you will be able to put all of your usernames in the usernames.txt file and when running check accounts it will put them all into the usernames.csv file witch will be used for logins.

**Comment by mervinpoh** [comment]
Yes im editing with notepad++ but at the moment i have nothing much to edit.. i am able to run it with 1 account. But if i were to use my own accounts in usernames.txt then it would fail since it will use a single password for all accounts.

Creating account doesnt work for me as i get

Exception calling "WriteAllLines" with "2" argument(s): "Value cannot be null.
Parameter name: contents"
At C:\Users\mervin\Desktop\PoGoMap-GUI\PokemonGo-Map\usernames.ps1:10 char:1
- [System.IO.File]::WriteAllLines($usernamesPath, $usernames)
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : ArgumentNullException

You cannot call a method on a null-valued expression.
At C:\Users\mervin\Desktop\PoGoMap-GUI\PokemonGo-Map\usernames.ps1:20 char:1
- $output = "username:[" + $output.trimend(',',1) + "]"
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "Replace" with "2" argument(s): "String cannot be of zero length.
Parameter name: oldValue"
At C:\Users\mervin\Desktop\PoGoMap-GUI\PokemonGo-Map\usernames.ps1:22 char:1
- $config = $config.replace("$line","$output")
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : ArgumentException
