### ISSUE TITLE
Map on mobil

### ISSUE THREAD

**Issue by jener8tionx** [engle2192/PoGoMap-GUI#17]
I am getting an error when trying to run Ngrok. "No connection could be made because the target machine actively refused it." Is there a setting that would allow me to get this working? 

Ngrok was working on the pokemongo-map all in one windows install so I don't think it is a router/port forwarding issue.

Thank you.

**Comment by jener8tionx** [comment]
Solved. I had to run ngrok like this:  ngrok http 192.168.0.101:5000.  New issue, ngrok hits the maximum free limit in like 5 min. Any option other than port forwarding to my IP address?

**Comment by Go2Engle** [comment]
You could possibly edit the config file using 127.0.0.1 because I think the map uses config over what's entered into the command line. So you should be able to change it there. That may break the view map button though.
