### ISSUE TITLE
is it still working?? cant log in accounts and pokealarm remore server failed??

### ISSUE THREAD

**Issue by Drak1314** [engle2192/PoGoMap-GUI#18]

**Comment by Go2Engle** [comment]
Did you run the check accounts first after upgrading? If so just check and make sure you have a usernames.CSV file in your pokemongo-maps folder. If you do then check the config file and make sure username and password are commented out. I made a change on where accounts are stored and used from. Not sure why your alarms aren't working though. Havnt changed anything with that.

**Comment by Drak1314** [comment]
i didnt upgrade .. and i check the account it said .. account must be deleted ?? been running it for days just it happened  now ..dont know  if they force update my region ,, maybe???

**Comment by Drak1314** [comment]
May i know how to start fresh do i just delete the folder?? or do i have something else to do ... sorry for this noob questions ..

**Comment by Go2Engle** [comment]
The accounts get banned after a few days that's why I included the account creator to make new accounts quicker. Also to upgrade just go to the github and grab the new installer and run it. It will place the new folder on your desktop. If your current is on the desktop I'd just delete it first.

**Comment by gavnasty** [comment]
How does the account creator work? I think PTC accounts need to be verified within 2 days. Otherwise the accounts stop working. That's why my accounts aren't working right now. All you have to do is click a button in the email, but I don't know what email address(es) the PTC accounts use.

**Comment by Go2Engle** [comment]
That is correct. You will need to keep making new accounts. I can add a box that you choose what email address all the confirmations come too if you'd like? It can be something I can add in one of the next releases.

**Comment by gavnasty** [comment]
Yeah, thatd be nice. I think others allow you to put in youremail+random@gmail.com so PTC thinks it's different gmail accounts, but they all get sent to the same one.

**Comment by Go2Engle** [comment]
Yeah that's correct. I can easily have that added :)

**Comment by gavnasty** [comment]
Awesome 👍
