### ISSUE TITLE
Nothing Showning?

### ISSUE THREAD

**Issue by Kirbyeats** [engle2192/PoGoMap-GUI#19]
I am a noob at this and apologize but when I run the map, I get 
[ Search-overseer][         schedulers][      Info] Finding Spawn points 10 steps away
[ Search-overseer][              models][      Info] Total of 0 spawns to track

so nothing is showing on the map, what did I Do incorrectly?

**Comment by Go2Engle** [comment]
Do you have spawn point scanning ticked? If so have you ran the map normally for a few hours first to find spawn points?

**Comment by Kirbyeats** [comment]
i have not ran it normally for a few hours, so i will do that and report back, and Yes, i do have it ticked.

**Comment by Go2Engle** [comment]
thats the issue then =] just run it normally for awhile first (it has to gather spawn points) then stop your map tick spawn point scanning then re-fire it back up and you should be golden!

**Comment by mervinpoh** [comment]
Is spawn point scanning more efficient?

**Comment by Go2Engle** [comment]
It takes less workers as it only scans areas where it knows spawn points are so you are not having wasted workers scan areas where Pokemon dont spawn.
