### ISSUE TITLE
 Cant connect to notification

### ISSUE THREAD

**Issue by Drak1314** [engle2192/PoGoMap-GUI#2]
it wont connect notification i already set it up for twitter 
ValueError: "No JSON object could be decoded"

**Comment by Go2Engle** [comment]
do you have quotes around each of your keys? also is the enable button checked?

**Comment by Drak1314** [comment]
YEs i did it all ... i dunno why it wont :(

**Comment by Go2Engle** [comment]
hmmm even if you are not using pushbullet or slack make sure what ever is in there API boxes has quotes around it also. They cant be left blank. try that for me.

**Comment by Drak1314** [comment]
TY its running now checking my twitter... :)

**Comment by Go2Engle** [comment]
No problem! Im gonna try and figure out a work around that for in the future!

**Comment by Drak1314** [comment]
TY so much ... not to be rude .. but one last thing do this support multi location scanning?? sorry im so noob on this ... TY so much for making this Easy .. :)

**Comment by Go2Engle** [comment]
NP man! and it dose not ATM, Could possibly add that in in the future. If you want to do multiple locations you would need to download multiple copies and setup each and then change the port numbers to different ports like 5001 and 4001 in the GUI. Just glad people are getting to use it =]

**Comment by Drak1314** [comment]
ok2 i will and Do it ... do you mind if i will comment here for help if i stumble a problem .. trying to set up my town and my Uni .. its hard out here only 6 pokestop in my town and same in my Uni .. spawn suck too.. this really help us ...

**Comment by Go2Engle** [comment]
yeah thats fine! glad to help when I can!
