### ISSUE TITLE
Username Problems

### ISSUE THREAD

**Issue by thecopter** [engle2192/PoGoMap-GUI#20]
Hey there, 

having 2 issues.

If i start up the gui, it says update available every time, even if i update.

The second: if i run map it cant get usernames. http://prntscr.com/ckaucv

Otherwise, thanks for the great work :)

**Comment by Go2Engle** [comment]
What version number is showing down in the bottom left hand corner of your GUI?

**Comment by thecopter** [comment]
3.1.5

**Comment by Go2Engle** [comment]
yeah the latest is 3.1.7. try running the updated application in your folder as a administrator(rightclick > run as administrator)

**Comment by thecopter** [comment]
Does not work but the version.txt says 3.1.7 :/

**Comment by Go2Engle** [comment]
Inside your pogomap-gui folder open an cmd window and type git pull origin master. Let me know if that updates it.

**Comment by thecopter** [comment]
Ah, he had some problem with the config. Deleted it and everything worked fine. Now hes missing the usernames.csv

**Comment by Go2Engle** [comment]
You need to create some new accounts if you don't have a usernames.txt file for it to create the CSV file. If you already have a usernames.txt file just run the account checker and it will create the CSV :) if that makes sense lol.

**Comment by thecopter** [comment]
And the case is solved, thank you very much :)
