### ISSUE TITLE
Don't know how to do on the 3rd step

### ISSUE THREAD

**Issue by iLander04** [engle2192/PoGoMap-GUI#22]
I don't know how to do in this, when I wrote something it says me this:

![captura](https://cloud.githubusercontent.com/assets/22351495/18720659/298561f0-802d-11e6-8e16-afcb52d5cf32.JPG)

**Comment by Go2Engle** [comment]
Did you run the AIO installer first?

**Comment by iLander04** [comment]
Yep, I did it

Obtener Outlook para Androidhttps://aka.ms/ghei36

On Wed, Sep 21, 2016 at 7:34 PM +0200, "engle2192" <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you run the AIO installer first?

##

**Comment by Go2Engle** [comment]
please manually try installing Pikaptcha from https://github.com/sriyegna/pikaptcha using his instructions then retry steps 1-3.
