### ISSUE TITLE
Error in "Run Notification" after updated

### ISSUE THREAD

**Issue by mactoy** [engle2192/PoGoMap-GUI#23]
After I updated , the map run smoothly however when i run the notification, it had error.

![image](https://cloud.githubusercontent.com/assets/22249095/18733716/019afc9a-80a0-11e6-8811-28ba07e6955a.png)

Regards,

mactoy

**Comment by Go2Engle** [comment]
Go to notifications settings and make sure all API boxes have " " in them even if you are not using that notification service.

**Comment by mactoy** [comment]
They already have " ". Same problem

**Comment by Go2Engle** [comment]
try rebooting your pc. if that works i may know what was wrong

**Comment by mactoy** [comment]
Already running. Thanks.
