### ISSUE TITLE
Account creater and check problems

### ISSUE THREAD

**Issue by thecopter** [engle2192/PoGoMap-GUI#25]
Hey,

me again :) So the accounts for scanning got banned. Somehow the program does not really recognize. It says that they may have been deleted and finishes the account creater routine after that.

Btw if anyone else experiences the problem with the update not working just delete the config.ini and run again. Works for me :)

![screenshot_1](https://cloud.githubusercontent.com/assets/22327325/18781919/2a7d65fa-8184-11e6-811d-c545ac132040.png)

**Comment by Go2Engle** [comment]
Yeah it does that that way if it was found banned then it removes them from your active accounts and then you can rebuild some more. And the error in your screenshot looks like you didn't define a password for your accounts :)

**Comment by thecopter** [comment]
_edit_ i did something wrong, nevermind, ty :)

**Comment by Go2Engle** [comment]
haha no problem! glad ya got it working.
