### ISSUE TITLE
Step-limit overruled by GUI

### ISSUE THREAD

**Issue by kamikzeNL** [engle2192/PoGoMap-GUI#26]
Hi,

The step-limit is limited to 20 in the GUI, whenever i set the stel-limit to 30 or 40 in the config, the GUI settings overrule the config settings.
Can this be changed to either, not overruling, or a GUI step limit of say 50?

Also wondering how you are using the usernames.csv for one server instance. Could be usefull to know, so that we can use the beehive with each their own username files. Would make getting banned a lot less ( i think ).
I got the beehive working... only 90 instances is a bit too much for even my computer.
Would like to have 9-18 beehives with each 10-15 accounts or so.

Keep up the good work man! Much appreciated.

~ Kamikze

**Comment by Go2Engle** [comment]
The little step count picker can be typed in also :) so you can put in any number you'd like. And the way the CSV file works is with the flag -ac usernames.csv. I've never looked into the beehive thing though so I prob won't be including that in the GUI but if I do it would be awhile from now. But thanks man! :)
