### ISSUE TITLE
Cant run map

### ISSUE THREAD

**Issue by Fasio91** [engle2192/PoGoMap-GUI#27]
After following all the installation-step. I click run map and I got this:
![pogomap](https://cloud.githubusercontent.com/assets/22413588/18808429/d5e9661c-8262-11e6-81d0-70da17b528bc.png)
 I cant "view map" or do something.
I must say when I click "config po-go map" in setup tab, I got an error but it closes fast, impossible to get a screenshot.
I tried to re-install all, but same problem.

**Comment by kamikzeNL** [comment]
On the map settings, enter a location. This is in a format lat,long, so for instance 51.12312,3.1234
That should remove that error.

**Comment by Go2Engle** [comment]
Thanks for answering for me :) you also can use zip code or an address in quotes :)
