### ISSUE TITLE
Account creation error

### ISSUE THREAD

**Issue by KERL0N** [engle2192/PoGoMap-GUI#28]
I have some problems during the account creation step. I hope you can help me.
I get this error:

> ImportError: DLL load failed: %1 is not a valid Win32 application.
> No valid accounts found! You will need to create new accounts in order to run your map.
> Press any key to continue . . .

**Comment by mikeclaussen** [comment]
I'm getting the same error.

**Comment by Go2Engle** [comment]
One of my other PCs are getting this as well. I'm going to have to look I to this. One thing I can think of to try is to completely uninstall Python and delete the python27 folder located at C:\python27

**Comment by Go2Engle** [comment]
So whatvi did was I just deleted my python27 folder and re-ran my AIO installer. Everything was good then. :)
