### ISSUE TITLE
Banned accounts

### ISSUE THREAD

**Issue by gesonchong** [engle2192/PoGoMap-GUI#29]
Should banned accounts (assuming the ones that say "It may have been deleted") automatically be erased from the usernames list? It seems to waste a lot of time while scanning saying that it it can't login to the PTC account.

**Comment by gesonchong** [comment]
http://imgur.com/mPibZ5k

This is the end result, not sure if it is important

**Comment by Go2Engle** [comment]
Yeah that's fine. When you run the account creator or the account checker accounts that are banned will be removed automatically.

**Comment by gesonchong** [comment]
What about the accounts that just say It may have been deleted? It continues to say that even after multiple account check runs
