### ISSUE TITLE
How to manually add users to config.ini ?

### ISSUE THREAD

**Issue by dr-antivirus** [engle2192/PoGoMap-GUI#3]
I currently have something like this, where to input the usernames ?```
# DO NOT USE NOTEPAD TO EDIT CONFIG FILES!! USE NOTEPAD ++ INSTEAD.
# Authentication settings
# auth-service:          # ptc (default) or google

password:[XXX]
# Database settings
# db-type: sqlite        # sqlite (default) or mysql
# db-host:               # required for mysql
# db-name:               # required for mysql

```
```

**Comment by dr-antivirus** [comment]
I currently have something like this, where to input the usernames ?```
# DO NOT USE NOTEPAD TO EDIT CONFIG FILES!! USE NOTEPAD ++ INSTEAD.
# Authentication settings
#auth-service:          # ptc (default) or google

password:[XXX]

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
```

**Comment by Go2Engle** [comment]
above password:[XXX] add username:[username1,username2,username3] so should look like

username:[username1,username2,username3]
password:[XXX]

if you have different passwords for each they have to be in the same order so like

username:[username1,username2,username3]
password:[password1,password2,password3]

**Comment by dr-antivirus** [comment]
Thank you very much !
Absolutely amazing work, though it took me about 4 hours to set it up correctly.
Using Windows 10 Home edition, I had to make some deep changes in OS settings and registry to make Powershell work correctly.
Keep it up !
PS: Is there any way to let the script running on my pc (scanning the area around my job location) and view the map remotely from my android mobile ? So if I find some interesting Pokemon, I can go and catch them ?

**Comment by Go2Engle** [comment]
Glad you got it working!

You can follow these instructions here: https://pgm.readthedocs.io/en/develop/extras/external.html
