### ISSUE TITLE
Virus alerts

### ISSUE THREAD

**Issue by SeanKempf** [engle2192/PoGoMap-GUI#32]
Running in Windows 10.  Everything had been going fine.  Now all of a sudden, the gui launcher executable is getting flagged as containing a trojan and will not run nor can I pull the newest commit off the github repository because it's immediately intercepted.

**Comment by Go2Engle** [comment]
Thats strange O.o can you make an exception in your virus scanner? Its probably flagging it because when it starts up it reaches out to my website to see what the latest version number is.

**Comment by SeanKempf** [comment]
After a little more troubleshooting, it's only firing up after I tried to use the mobile access button.  I don't like making AV exceptions so I just used normal port forwarding in my router and use a ddns address to hit it.  Thanks for the response!

**Comment by Go2Engle** [comment]
Hmmm must not like ngrok or curl lol. Opening ports is better anyways. i just put that in there for people that didnt wanna go through that! Glad your all set though!
