### ISSUE TITLE
3.2.4 steps limited

### ISSUE THREAD

**Issue by teknogeek1300** [engle2192/PoGoMap-GUI#34]
Can't put in manual value in GUI v 3.2.4, maxed at 20. I use 45+.

**Comment by Go2Engle** [comment]
Please close the GUI go into your prereqs folder and run the TroubleshootUpdate.bat. I just added more numbers. after bat runs re-open GUI and check.

**Comment by Go2Engle** [comment]
shit if you just did that do it again. i re-uploded an old copy new is in now

**Comment by teknogeek1300** [comment]
Ok, I just noticed it reverted, stuck in update loop. haha

**Comment by Go2Engle** [comment]
Try just running the bat file again. If it dosnt update paste what the bat file says in here.
