### ISSUE TITLE
Scanner Runs but now Spawns Detected

### ISSUE THREAD

**Issue by sudarsk** [engle2192/PoGoMap-GUI#35]
I went through all the setsp but end up with this:

http://puu.sh/rsVMk/e4f90bc329.png

What am I doing wrong?

**Comment by Go2Engle** [comment]
You could be IP banned. Connect to the game on your phone while connected to your network. If nothing shows up your prob IP banned. They usly last a little while.

**Comment by sudarsk** [comment]
Hello engle! Thanks for taking your time.

As it is I can connect to my the game on my Home's WiFi and I can see and spins PokeStops.

also I tried to do the PowerShell steps but ended up with this: http://puu.sh/rsW9q/4aa20a66b4.png

So I followed someone's directions and did it manually.

**Comment by sudarsk** [comment]
I finally made it to work, the option Scan Spawn was active. I disable it and it started!

Thank you for the amazing work!!

**Comment by Go2Engle** [comment]
ahhh that will do it also! Glad you figured it out!
