### ISSUE TITLE
Auto Updater not Working?

### ISSUE THREAD

**Issue by sudarsk** [engle2192/PoGoMap-GUI#38]
Hello engle, sorry to bother you again, but this time is the autoupdater that is not working. it appears to download everything and tells me to close the updater window, but when I open the PoGo GUI again, it still ask me to update.

What could It be the problem?

Is there a way to save the current data (accounts, spawn data, spawn points), and donwload the newest version from the gitgub?

Thanks in advance!

**Comment by thecopter** [comment]
Having the same problem. Update seems to be running but after opening the gui it always tell me the latest version is available.

**Comment by Go2Engle** [comment]
Check in your prereqs folder and see if you have a forceupdate.bat and try that for me quick. Also is your updater.exe icon have a blue symbol or is it generic?

**Comment by thecopter** [comment]
I for myself have only the troubleshootupdate.bat and it does nothing. The icon of my updater is blue like it should be.

**Comment by sudarsk** [comment]
Ditto.

Is there anyway you can send us that forceupdate.bat?

**Comment by Go2Engle** [comment]
ok try this for me. While you are in the pogomap-GUI folder hold shift and right click an empty spot and choose open commandline here. Then type 'git reset --hard' hit enter then type 'git pull' and hit enter. that should force update you and get everything up to date. let me know if that does the trick.

**Comment by thecopter** [comment]
Worked for me. Thanks again :)

**Comment by Go2Engle** [comment]
awesome! hopfully going forward everything should work with no issues!

**Comment by sudarsk** [comment]
Im getting this message: http://puu.sh/rwO2V/0d2b50786b.png

Thanks for the help engle.

**Comment by Go2Engle** [comment]
Try deleting the file that it mentions in there then reboot and try that command again.

**Comment by sudarsk** [comment]
Done!
Props for you man!

**Comment by Go2Engle** [comment]
Woop woop! Glad its working now!
