### ISSUE TITLE
Location Issue

### ISSUE THREAD

**Issue by xXDark33Xx** [engle2192/PoGoMap-GUI#4]
![hmmm](https://cloud.githubusercontent.com/assets/20673065/18604958/4ddfba74-7c53-11e6-8554-8a249ab21a2e.PNG)
when i run it this shows up :/

**Comment by Go2Engle** [comment]
You need to enter a zip code or coordinates in the main GUI =]

**Comment by xXDark33Xx** [comment]
i thought that was for some zip file i didnt know about, i edited the location in comfig xD, thnx for your quick reply

**Comment by Go2Engle** [comment]
no problem! if you comment out the zip in the config file you can use the GUI in the future! dont edit your current setup to much though, just released an installer that has built in updater so future updates you dont lose your current setup. :D

**Comment by xXDark33Xx** [comment]
how do i add coordinates btw, instead or zip code?

**Comment by Go2Engle** [comment]
In format like 473919475,-92948582948
