### ISSUE TITLE
Twitter notification problem

### ISSUE THREAD

**Issue by marcelotvaz** [engle2192/PoGoMap-GUI#42]
Hello,
first of all, congratulations for your program, its amazing, but i'm having some problems with the notifications. i already put every token and key at the blank spaces, and verified if they are in the quotes. but everytime i run the notifications i get this error:

http://imgur.com/a/Gscjs

How can I solve this?

**Comment by Go2Engle** [comment]
please refer to issue #28 this should help you

**Comment by marcelotvaz** [comment]
thanks, it worked

**Comment by Go2Engle** [comment]
Awesome glad to hear!
