### ISSUE TITLE
account creation error

### ISSUE THREAD

**Issue by marcelotvaz** [engle2192/PoGoMap-GUI#45]
Hello, today I had to reinstall everything, and now, when i try to create new accounts this happens:
http://imgur.com/nXtjd2E
I already rebooted my computed; tried to reinstall pikaptcha; uninstalled phyton27, deleted the folder and installed again.
What it could be?

**Comment by Go2Engle** [comment]
Do you have google chrome installed on your PC?

**Comment by marcelotvaz** [comment]
Yes

**Comment by Go2Engle** [comment]
Download http://go2engle.com/downloads/chromedriver.exe and place it in your C:\python27\scripts\ folder

**Comment by Go2Engle** [comment]
after doing that restart the GUI and try again

**Comment by marcelotvaz** [comment]
everything is running smoothly right now
