### ISSUE TITLE
Notifications Error

### ISSUE THREAD

**Issue by xXDark33Xx** [engle2192/PoGoMap-GUI#5]
![capture](https://cloud.githubusercontent.com/assets/20673065/18605394/561535aa-7c5f-11e6-99c4-78fa1a9930de.PNG)

**Comment by Go2Engle** [comment]
Please check under the closed issues section. :)

**Comment by Go2Engle** [comment]
https://github.com/engle2192/PoGoMap-GUI/issues/2

**Comment by xXDark33Xx** [comment]
Thnx, sorry xD im starting to bug u

**Comment by Go2Engle** [comment]
No not at all :)
