### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by xXDark33Xx** [engle2192/PoGoMap-GUI#6]
i dont know if this is allowed, but is there a section for ideas or if u have reddit i can msg u

**Comment by Go2Engle** [comment]
There is not a section but for now we can use this until I think of something better lol.

**Comment by xXDark33Xx** [comment]
ok, i was thinking about filter for ivs in pokealarms but i dont know whether to post that here, in pokealarms or in map-ivs xD

**Comment by Go2Engle** [comment]
Haha you would want to post that in pokealarm. The creator of pokemap IVs already has the webhooks. Poke alarm just needs to look for them.

**Comment by xXDark33Xx** [comment]
is there a way to have 2 locations running or no?

**Comment by Go2Engle** [comment]
You would need to have 2 directories at the moment.

**Comment by Go2Engle** [comment]
We now have a place for ideas! Http://www.go2engle.com there is a section for feature requests.
