### ISSUE TITLE
No pokemon showing on the map

### ISSUE THREAD

**Issue by dr-antivirus** [engle2192/PoGoMap-GUI#8]
Hello
Until 2 hours ago, everything was fine and 100% working.
Suddenly, all pokemon disappeared from the maps, but I can still see spawns, Pokestops and gyms.
I tried on 2 different installations of the tool, with different ports and locations and still no results.
What to do ?

Edit : working again now after about 2 hours of outage. Didn't change anything, the script was running and finding nothing, then suddenly started finding pokemon without any change from my side.

Maybe Niantic are experimenting a new security system ?

**Comment by Go2Engle** [comment]
Your accounts may have been banned already. try using the account creator to make some more accounts.

**Comment by dr-antivirus** [comment]
Tried new accounts at first without any changes. But then it decided to work again after about 30 minutes of running without getting pokemons.

**Comment by Go2Engle** [comment]
hmmm strange. possibly a temp IP ban?

**Comment by dr-antivirus** [comment]
Dunno .. anyway what matters now is that it's working fine :)
Thank you :)
