### ISSUE TITLE
I can't find the folder

### ISSUE THREAD

**Issue by legendz97** [engle2192/PoGoMap-GUI#9]
The folder is not in my desktop... how do I find it?

**Comment by Go2Engle** [comment]
After running the installer? if so just re run it one more time. I'm looking into that issue right now.

**Comment by legendz97** [comment]
I've done it, this is what it shows me
https://snap.ashampoo.com/GnLJE7Ze
"Done. You can close this now"

**Comment by Go2Engle** [comment]
and there is no PoGoMap-GUI folder in the same directory that you are running the installer from?

**Comment by legendz97** [comment]
I run it from the Downloads folder and there is nothing there, I've tried by searching the PoGoMap-GUI folder.

**Comment by legendz97** [comment]
Which folder does the installer check when installing, so it can state "Done. You can close this now"

**Comment by Go2Engle** [comment]
strange not sure why the installer is not working for you. you can manually try cloning the repo. just open a command window in the folder you want to install to and do git clone https://github.com/engle2192/PoGoMap-GUI.git My "installer" is really only checking to make sure you have git installed. if it is it does the git clone. if git is not installed in downloads and installs git then runs the git clone. the "Done. You can close this now" is just generic at the moment and comes up after git clone runs. Currently if there is an error running the git clone command you wouldnt see it. Bad coding on my behalf. Try my suggestion and manually do git clone and see if that works.

**Comment by legendz97** [comment]
Okay, I got it working, but I got more problems now...
So, when I try to run the map, I get  "[MainThread][runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server"

I'm using my own accounts and they are listed like 
auth-service:ptc
username:[account1,account2,account3]
password:[password1,password,password3]

What am I doing wrong?

And I also can't run gpedit.msc

**Comment by Go2Engle** [comment]
Try running the pogomap configure button again. If still not working after that try manually running npm install from within the pokemongo-map directory.

**Comment by legendz97** [comment]
https://snap.ashampoo.com/zAFKeIdM

I get some errors, and by the way, there is always a new update, like, it keeps saying that there is a new update after we update the app

**Comment by legendz97** [comment]
https://snap.ashampoo.com/zAFKeIdM

I get this errors, and there is update bug where the update notification just keeps showing up after we udate

**Comment by Go2Engle** [comment]
I think something may be wrong with your setup. Everyrhing is working on my test setup and im not getting notifications once its updated. I just uploaded a new AIO installer under releases. Try downloading and using that. This will install all pre reqs and clone a fresh copy of the repo to your desktop. Once you run that reboot your computer and then run the last few install steps under the install button.

**Comment by legendz97** [comment]
Okay, it's fully updated, rebooted and everything, but I get this now..
https://snap.ashampoo.com/qai5DVTW

So awkward that I get so many errors :(
Sorry for the trouble

**Comment by Go2Engle** [comment]
That's an easy one now :) you just need to enter a zip code in the starting zip box :) and no worries man!

**Comment by legendz97** [comment]
https://snap.ashampoo.com/PzvFsaAm
Dammit... give me a e.g. of a zip code you've used.. wtf...

**Comment by Go2Engle** [comment]
Hmm well that's not related to the zip now. To me it looks like you need to re-run the configure pogomap button. If you still get it try running npm install manually from within the pokemongo-map directory!

**Comment by Go2Engle** [comment]
You still having troubles with this? or can this be closed?

**Comment by legendz97** [comment]
I was not able to make it work, but I'm moving on and use another. 
Sorry for using your time
